### ISSUE TITLE
[python-package] rabit.tracker_print not outputting logs

### ISSUE THREAD

**Issue by chaosmail** [dmlc/xgboost#1014]
Hi guys,

I ran into the strange problem, that even though enabling the `verbose` option, there are no logs printed during the training. However, when I replace `rabit.tracker_print` with `print` everything works fine. Any idea how to solve this, any secret option? Thanks for help and hints!

I am on Ubuntu 15.10 64bit, python3.4 running via Jupyter (XGB compiled via make -j4), here is an excerpt from my code.

```python
import xgboost as xgb

params = {
    'max_depth': 5,
    'n_estimators': 100,
    'learning_rate': 0.05,
    'gamma': 0.25,
    'subsample': 0.9,
    'colsample_bytree': 0.9,
    'seed': 42,
}

fit_params = {
    'early_stopping_rounds': 20,
    'eval_metric': 'auc',
    'eval_set': [(X_test.values, y_test.values)],
}

clf = xgb.XGBClassifier(**params)
clf.fit(X_train.values, y_train.values, **fit_params)
```

Best,
Christoph

**Comment by tqchen** [comment]
hmm, could due to flush behavior of the logs. so they are not immediately flushed. Can you check if the print happens if you use say python console?

**Comment by Far0n** [comment]
@tqchen is there a way to force the flush? I got the same problem (burst of msg-lines), if I use an IDE like Pycharm, everything works normal from terminal though.

**Comment by chaosmail** [comment]
Yeah most likely it is not getting flushed properly, because in some situations it does work. I wonder if there is a specific reason for using the `rabit` package for logs in python instead of the internal [`logging`](https://docs.python.org/3.4/library/logging.html) module. I do understand that `rabit` does much more than just writing logs, however the `logging` module is the best choice for logs in python. I could send a PR for the `python-package` if this is interesting for the project.

**Comment by tqchen** [comment]
I will add a force flush in next PR. The reason to use rabit is to enable same code to ship to distributed settings and have the message show on user's side

**Comment by chaosmail** [comment]
@tqchen alright thanks a lot!

**Comment by tqchen** [comment]
should be fixed by #1102

**Comment by khozzy** [comment]
Hi, was that fixed? I'm running latest code (compiled with `make -j4`) and still cannot get logs in Jupyter notebook.

```python
params = {
    'objective':'binary:logistic',
    'max_depth':2,
    'silent':0,
    'eta':1
}

num_rounds = 5
bst = xgb.train(params, dtrain, num_rounds, verbose_eval=True)
```
The only output I get in the console is:

```bash
[06:14:52] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[06:14:52] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 6 extra nodes, 0 pruned nodes, max_depth=2
[06:14:52] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
[06:14:52] src/tree/updater_prune.cc:74: tree pruning end, 1 roots, 4 extra nodes, 0 pruned nodes, max_depth=2
```
