### ISSUE TITLE
[jvm-package]How to build xgboost4j in win7-64bit system.

### ISSUE THREAD

**Issue by baibaiw5** [dmlc/xgboost#1051]
I already built xgboost.exe and libxgboost.dll successfully in win7-b4bit system.
--But when I built xgboost4j using "mvn package",I got the following code check error:
$ mvn package
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for ml.dmlc:xgboost4j:jar:0.5
[WARNING] 'build.plugins.plugin.version' for org.codehaus.mojo:exec-maven-plugin is missing. @ line 32, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] xgboost-jvm
[INFO] xgboost4j
[INFO] xgboost4j-spark
[INFO] xgboost4j-flink
[INFO] xgboost4j-example
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost-jvm 0.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost-jvm ---
[WARNING] sourceDirectory is not specified or does not exist value=D:\Develop\XGBoost\xgboost-v2\xgboost\jvm-packages\src\main\scala
[WARNING] testSourceDirectory is not specified or does not exist value=D:\Develop\XGBoost\xgboost-v2\xgboost\jvm-packages\src\test\scala
Processed 0 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 102 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost-jvm ---
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (default) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:compile (compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:testCompile (test-compile) @ xgboost-jvm ---
[WARNING]  Expected all dependencies to require Scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-compiler:2.10.5 requires scala version: 2.10.5
[WARNING]  org.scala-lang:scala-reflect:2.10.5 requires scala version: 2.10.5
[WARNING]  ml.dmlc:xgboost-jvm:0.5 requires scala version: 2.10.5
[WARNING]  org.scalatest:scalatest_2.10:2.2.6 requires scala version: 2.10.6
[WARNING] Multiple versions of scala libraries detected!
[INFO] No sources to compile
[INFO]
[INFO] --- scalatest-maven-plugin:1.0:test (test) @ xgboost-jvm ---
Discovery starting.
Discovery completed in 239 milliseconds.
Run starting. Expected test count is: 0
DiscoverySuite:
Run completed in 315 milliseconds.
Total number of tests run: 0
Suites: completed 1, aborted 0
Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
No tests were executed.
[INFO]
[INFO] --- maven-assembly-plugin:2.6:single (make-assembly) @ xgboost-jvm ---
[INFO] Assemblies have been skipped per configuration of the skipAssembly parameter.
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building xgboost4j 0.5
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- scalastyle-maven-plugin:0.8.0:check (checkstyle) @ xgboost4j ---
Processed 7 file(s)
Found 0 errors
Found 0 warnings
Found 0 infos
Finished in 1044 ms
[INFO]
[INFO] --- maven-checkstyle-plugin:2.17:check (checkstyle) @ xgboost4j ---
[INFO] There are 78 errors reported by Checkstyle 6.11.2 with checkstyle.xml ruleset.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[2] (regexp) RegexpSingleline: No trailing whitespace allowed.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[7] (regexp) RegexpSingleline: No trailing whitespace allowed.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[21] (sizes) LineLength: Line is longer than 100 characters (found 104).
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[26,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[26,37] (naming) MethodName: Method name 'XGBGetLastError' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[28,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[28,34] (naming) MethodName: Method name 'XGDMatrixCreateFromFile' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[30,9] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[30,27] (naming) MethodName: Method name 'XGDMatrixCreateFromDataIter' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[33,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[33,34] (naming) MethodName: Method name 'XGDMatrixCreateFromCSR' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[36,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[36,34] (naming) MethodName: Method name 'XGDMatrixCreateFromCSC' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[39,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[39,34] (naming) MethodName: Method name 'XGDMatrixCreateFromMat' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[42,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[42,34] (naming) MethodName: Method name 'XGDMatrixSliceDMatrix' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[44,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[44,34] (naming) MethodName: Method name 'XGDMatrixFree' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[46,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[46,34] (naming) MethodName: Method name 'XGDMatrixSaveBinary' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[48,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[48,34] (naming) MethodName: Method name 'XGDMatrixSetFloatInfo' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[50,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[50,34] (naming) MethodName: Method name 'XGDMatrixSetUIntInfo' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[52,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[52,34] (naming) MethodName: Method name 'XGDMatrixSetGroup' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[54,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[54,34] (naming) MethodName: Method name 'XGDMatrixGetFloatInfo' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[56,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[56,34] (naming) MethodName: Method name 'XGDMatrixGetUIntInfo' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[58,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[58,34] (naming) MethodName: Method name 'XGDMatrixNumRow' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[60,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[60,34] (naming) MethodName: Method name 'XGBoosterCreate' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[62,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[62,34] (naming) MethodName: Method name 'XGBoosterFree' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[64,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[64,34] (naming) MethodName: Method name 'XGBoosterSetParam' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[66,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[66,34] (naming) MethodName: Method name 'XGBoosterUpdateOneIter' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[68,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[68,34] (naming) MethodName: Method name 'XGBoosterBoostOneIter' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[71,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[71,34] (naming) MethodName: Method name 'XGBoosterEvalOneIter' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[74,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[74,34] (naming) MethodName: Method name 'XGBoosterPredict' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[77,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[77,34] (naming) MethodName: Method name 'XGBoosterLoadModel' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[79,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[79,34] (naming) MethodName: Method name 'XGBoosterSaveModel' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[81,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[81,34] (naming) MethodName: Method name 'XGBoosterLoadModelFromBuffer' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[83,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[83,34] (naming) MethodName: Method name 'XGBoosterGetModelRaw' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[85,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[85,34] (naming) MethodName: Method name 'XGBoosterDumpModel' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[88,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[88,34] (naming) MethodName: Method name 'XGBoosterGetAttr' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[89,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[89,34] (naming) MethodName: Method name 'XGBoosterSetAttr' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[90,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[90,34] (naming) MethodName: Method name 'XGBoosterLoadRabitCheckpoint' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[91,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[91,34] (naming) MethodName: Method name 'XGBoosterSaveRabitCheckpoint' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[94,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[94,34] (naming) MethodName: Method name 'RabitInit' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[95,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[95,34] (naming) MethodName: Method name 'RabitFinalize' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[96,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[96,34] (naming) MethodName: Method name 'RabitTrackerPrint' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[97,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[97,34] (naming) MethodName: Method name 'RabitGetRank' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[98,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[98,34] (naming) MethodName: Method name 'RabitGetWorldSize' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[99,16] (modifier) ModifierOrder: 'static' modifier out of order with the JLS suggestions.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[99,34] (naming) MethodName: Method name 'RabitVersionNumber' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9_]*$'.
[ERROR] src\main\java\ml\dmlc\xgboost4j\java\XGBoostJNI.java:[100] (regexp) RegexpSingleline: No trailing whitespace allowed.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] xgboost-jvm ........................................ SUCCESS [  4.874 s]
[INFO] xgboost4j .......................................... FAILURE [  1.838 s]
[INFO] xgboost4j-spark .................................... SKIPPED
[INFO] xgboost4j-flink .................................... SKIPPED
[INFO] xgboost4j-example .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.894 s
[INFO] Finished at: 2016-03-28T19:09:16+08:00
[INFO] Final Memory: 25M/279M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project xgboost4j: You have 78 Checkstyle violations. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xgboost4j

--Besides,In create_jni.bat ,it mentions xgboost4j.dll and "source library not found, please build it first from ..\windows\xgboost.sln";but in create_jni.sh,it mentions libxgboost4j.so.
I can not find xgboost.sln or xgboost4j.dll in git repository,How can I get them?

**Comment by CodingCat** [comment]
@baibaiw5 , I'm sorry that xgboost4j is not support for windows temporarily .....

**Comment by marcus-voss** [comment]
Any Plans on when this will be avail?

**Comment by lovetimil** [comment]
come arcross the same problem. where to got xgboost4j.dll,just xgboost4j.dll.

**Comment by alaeddinms** [comment]
Has xgboost4j.dll for windows been added? where to get it please?

Thanks

**Comment by syw2014** [comment]
I have the same errors, has it solved now?

**Comment by xmbipb** [comment]
Also have the same errors. Win 10 64 Bit.
Why is not it possible to provide a JAR somewhere?

**Comment by johnlevi** [comment]
Can support windows in 0.7? 
 I build it in eclipse(windows) still failed.

**Comment by sahil1421011** [comment]
anyone get the solution for this issue ??? I hope now xgboost supported in windows.

**Comment by lujinyong168** [comment]
I hope now xgboost0.7 supported in windows.

**Comment by superbobry** [comment]
The JVM/Spark version does indeed support Windows. In fact, we test all incoming changes on Windows as well as Linux/OSX: https://ci.appveyor.com/project/tqchen/xgboost/
