### ISSUE TITLE
WindowsError: exception: access violation reading 0x0000000100000008

### ISSUE THREAD

**Issue by lwclark** [dmlc/xgboost#1163]
I've installed XGB on two independent VMs, one running Windows 10 and the other running Windows Server 2013. On both installs, when testing with "python basic-walkthrough.py" or when trying to invoke XGB from a Jupyter notebook, execution halts with this exception:

WindowsError: exception: access violation reading 0x0000000100000008

I've tried starting the jupyter notebook from an administrative command prompt, with the same result.

Any advice welcome. Thank you.

**Comment by khotilov** [comment]
To separate out python-related issues, you may build the xgboost executable and then try some CLI demo, e.g., https://github.com/dmlc/xgboost/tree/master/demo/binary_classification and see if the problem persists.

**Comment by emuchogu** [comment]
Got the same issues after installing on windows 10 using instructions I found here https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en.

**Comment by emuchogu** [comment]
Fixed the issue by moving the path reference for MinGW-W64 to the front of the PATH system variable.
Cleaned, rebuilt an re-installed xgboost. Problem solved.

**Comment by harishneela** [comment]
Hi ,I am still facing the same issue. I tried to move path reference to front but of no use. Can you please help me  with this? I have installed xgboost using link by emuchogu.

please find below error in ipython console


  **File "<ipython-input-6-40e2638c9788>", line 1, in <module>
    xgb.cv(params= params, nfold=5, dtrain=xgtrain,num_boost_round=1000)

  File "C:\Users\user\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\training.py", line 367, in cv
    cvfolds = mknfold(dtrain, nfold, params, seed, metrics, fpreproc, stratified, folds)

  File "C:\Users\user\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\training.py", line 244, in mknfold
    dtrain = dall.slice(np.concatenate([idset[i] for i in range(nfold) if k != i]))

  File "C:\Users\user\Anaconda3\lib\site-packages\xgboost-0.6-py3.5.egg\xgboost\core.py", line 544, in slice
    ctypes.byref(res.handle)))


OSError: exception: access violation reading 0x000000000B525D0C **

I know that error is something related to c++ and c. But i am not able to figure out the actual issue.

Thanks for responding.

**Comment by partmor** [comment]
I encountered the exception: access violation reading 0x0000000100000008 when using the .fit() method of the XGB classifier. 

None of the solutions here, or elsewhere helped me.

Finally the **only thing that worked** for me was running my scripts (or executing jupyter notebook) on **Windows command line (cmd) rather than git-bash**.

Hope this helps you

**Comment by lugq1990** [comment]
I also find this problem during working in the windows using the **cmd** terminal for using the LightGBM(like the XGBoost). I try many ways for solving that, but finally if I **delete** the lgb_train and lgb_test and make the Datasets again, that will make it model start to train.
