### ISSUE TITLE
C API Support More Robust Creation from Sparse Matrix

### ISSUE THREAD

**Issue by tqchen** [dmlc/xgboost#1583]
There are several issues complaining about sparse feature format and incorrect dimension matching. This should be fixed. Let us do the following fix
- Add XGBoostDMatrixCreateFromCSREx, and XGBoostDMatrixCreateFromCSREx, which take additional num_col and num_row arguments
- Mark original Creation function as deprecated, and update most front-end API to the new version

@khotilov Interested in do a PR on this?

**Comment by khotilov** [comment]
Yes, I'll give it a try.
Would it make sense to leave, e.g., automatic row counting that could be turned on by a call with num_row set to 0?

**Comment by tqchen** [comment]
sounds good

**Comment by BlindApe** [comment]
I'm sorry but I don't know C++ for contribute to this, but I've tested xgboost from the begining with extra datasets finding several limits that were fixed by @tqchen and @hetong007  (thanks!).
I'll promise check the limits again with the new sparse data ingestion.
Meanwhile I want remember some of my previous experience. I hope can help a bit:
# 517

**Comment by masonsydney** [comment]
@tqchen  Could you please answer my question like below? Thanks a lot.
https://github.com/dmlc/xgboost/issues/1571

**Comment by khotilov** [comment]
I've just started looking into it, but got side-tracked with the issue that @BlindApe has pointed...

@tqchen : in light of that hitting-type-limits issue, would it make sense to change the interface of the new XGDMatrixCreateFrom* to use `uint64_t` instead of `unsigned long`? In Windows, long is 32 bit with MinGW and VC, while it's 64 bit in unix-derivatives. I doubt that there currently are people doing such heavy lifting in windows, but I'm sure there will be problems in a year or two. It might be not safe to just redefine `bst_uint` to be `uint64_t` though.

@BlindApe : the easiest solution for you currently would be to write your data into libsvm format (just don't do it from plain R, as it would take ages). Then you can ingest it directly into DMatrix and even use the file-cached processing. 

I see that the Matrix package currently has somewhat incomplete support for the long vector indexing (i.e., you can create a triplet sparse matrix with over 2^31 elements, but it wouldn't convert it to CSC format). But even if you would create a huge `dgCMatrix` manually, the current xgboost R-interface would not be able to handle it, as it uses 32 bit `int` and LENGTH(x) to get numbers of elements (that could be fixed).

I am not sure though how generally useful it would be to have a separate sparse triplet source for DMatrix (other then to compensate for the current shortcomings of the Matrix package).

**Comment by tqchen** [comment]
I think we can go with ```size_t``` in the new interface, which should be consistent with the maximum size

**Comment by khotilov** [comment]
That would work.
I usually prefer types of specific size, but I can see how it could be a problem if some architecture would not have that size.

**Comment by BlindApe** [comment]
@khotilov , my problem with libsvm format is that I usually use data.table for intensive data preprocessing, data grouping by, ... so I would need write the libsvm format from R, and as you say it is a pain.
Read libsvm for xgboost take advance because I can use a fresh R sessión without data.table load in memory, but it is neccesary a data transposition in the xgboost side (Internally I think xgboost uses column based representation, but not sure of this). 
The optimal data ingestion should be in a way xgboost don't need this transposition step, I think.

**Comment by minddrummer** [comment]
has this been fixed in 0.6? I am using 0.6 version via sklearn, and still have such issue. thanks!

**Comment by pheman** [comment]
I still have the same problem in my code, when the matrix is significantly sparse. Is the bug fixed?

**Comment by kayibal** [comment]
It is fixed if you install xgboost from source. The version on PyPi is quite old..

**Comment by Fryie** [comment]
I installed from source and get the following behaviour:
```python
>>> xgboost.DMatrix([0 for i in range(0,300)]).feature_names
[]
```
By contrast:
```python
>>> xgboost.DMatrix([0.1 for i in range(0,300)]).feature_names
['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f58', 'f59', 'f60', 'f61', 'f62', 'f63', 'f64', 'f65', 'f66', 'f67', 'f68', 'f69', 'f70', 'f71', 'f72', 'f73', 'f74', 'f75', 'f76', 'f77', 'f78', 'f79', 'f80', 'f81', 'f82', 'f83', 'f84', 'f85', 'f86', 'f87', 'f88', 'f89', 'f90', 'f91', 'f92', 'f93', 'f94', 'f95', 'f96', 'f97', 'f98', 'f99', 'f100', 'f101', 'f102', 'f103', 'f104', 'f105', 'f106', 'f107', 'f108', 'f109', 'f110', 'f111', 'f112', 'f113', 'f114', 'f115', 'f116', 'f117', 'f118', 'f119', 'f120', 'f121', 'f122', 'f123', 'f124', 'f125', 'f126', 'f127', 'f128', 'f129', 'f130', 'f131', 'f132', 'f133', 'f134', 'f135', 'f136', 'f137', 'f138', 'f139', 'f140', 'f141', 'f142', 'f143', 'f144', 'f145', 'f146', 'f147', 'f148', 'f149', 'f150', 'f151', 'f152', 'f153', 'f154', 'f155', 'f156', 'f157', 'f158', 'f159', 'f160', 'f161', 'f162', 'f163', 'f164', 'f165', 'f166', 'f167', 'f168', 'f169', 'f170', 'f171', 'f172', 'f173', 'f174', 'f175', 'f176', 'f177', 'f178', 'f179', 'f180', 'f181', 'f182', 'f183', 'f184', 'f185', 'f186', 'f187', 'f188', 'f189', 'f190', 'f191', 'f192', 'f193', 'f194', 'f195', 'f196', 'f197', 'f198', 'f199', 'f200', 'f201', 'f202', 'f203', 'f204', 'f205', 'f206', 'f207', 'f208', 'f209', 'f210', 'f211', 'f212', 'f213', 'f214', 'f215', 'f216', 'f217', 'f218', 'f219', 'f220', 'f221', 'f222', 'f223', 'f224', 'f225', 'f226', 'f227', 'f228', 'f229', 'f230', 'f231', 'f232', 'f233', 'f234', 'f235', 'f236', 'f237', 'f238', 'f239', 'f240', 'f241', 'f242', 'f243', 'f244', 'f245', 'f246', 'f247', 'f248', 'f249', 'f250', 'f251', 'f252', 'f253', 'f254', 'f255', 'f256', 'f257', 'f258', 'f259', 'f260', 'f261', 'f262', 'f263', 'f264', 'f265', 'f266', 'f267', 'f268', 'f269', 'f270', 'f271', 'f272', 'f273', 'f274', 'f275', 'f276', 'f277', 'f278', 'f279', 'f280', 'f281', 'f282', 'f283', 'f284', 'f285', 'f286', 'f287', 'f288', 'f289', 'f290', 'f291', 'f292', 'f293', 'f294', 'f295', 'f296', 'f297', 'f298', 'f299']
```

I believe that's related since the error appears due to `num_cols` returning 0.

**Comment by ciphurus** [comment]
Hi - is this solved? I am using sparse matrices in python. Building a model using a sparse matrix and then scoring on same sparse matrix still gives a feature name error. I am using '0.7' version. Can someone please suggest what to do here? Thanks.
