### ISSUE TITLE
Installation fails due to relative path

### ISSUE THREAD

**Issue by MaxBenChrist** [dmlc/xgboost#1932]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

## Environment info
Operating System: Ubuntu 16.04

After compiling, setup.py fails during installation of package

```bash
max@tuk:~/Documents/xgboost$ cd python-package; sudo python setup.py install
Install libxgboost from: ['/home/max/Documents/xgboost/python-package/xgboost/../../lib/libxgboost.so']
running install
running bdist_egg
running egg_info
creating xgboost.egg-info
writing requirements to xgboost.egg-info/requires.txt
writing xgboost.egg-info/PKG-INFO
writing top-level names to xgboost.egg-info/top_level.txt
writing dependency_links to xgboost.egg-info/dependency_links.txt
writing manifest file 'xgboost.egg-info/SOURCES.txt'
reading manifest file 'xgboost.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'xgboost/include'
warning: no files found matching '*' under directory 'xgboost/src'
warning: no files found matching '*' under directory 'xgboost/make'
warning: no files found matching '*' under directory 'xgboost/rabit'
warning: no files found matching '*' under directory 'xgboost/lib'
warning: no files found matching '*' under directory 'xgboost/dmlc-core'
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.a' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'xgboost.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/xgboost
copying xgboost/rabit.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/compat.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/core.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/training.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/plotting.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/sklearn.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/__init__.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/callback.py -> build/lib.linux-x86_64-2.7/xgboost
copying xgboost/libpath.py -> build/lib.linux-x86_64-2.7/xgboost
error: Error: setup script specifies an absolute path:

    /home/max/Documents/xgboost/python-package/xgboost/../../lib/libxgboost.so

setup() arguments must *always* be /-separated paths relative to the
setup.py directory, *never* absolute paths.
```

**Comment by diver-in-sky** [comment]
I've hacked `setup.py` by adding two lines (to change lib path from absolute to relative) and after that xgboost was successfully installed.

```
CURRENT_ABSOLUTE = os.path.dirname(os.path.realpath(__file__))
# replace LIB_PATH definition
LIB_PATH = [libpath['find_lib_path']()[0].replace(CURRENT_ABSOLUTE + '/', '')]
```

**Comment by nkeywal** [comment]
Same problem here (on Ubuntu 14.04, Python 3.4), the fix mentioned above worked.

**Comment by diver-in-sky** [comment]
@MaxBenChrist @nkeywal could you please update master and check if your problem has been fixed?

**Comment by MaxBenChrist** [comment]
It has been fixed. Everything is working fine now. Thank you very much :)

**Comment by Vanban-Wu** [comment]
Hi everyone,
I am a MacOS (Sierra) user. Which file am I suppose to add the two statements described below:

CURRENT_ABSOLUTE = os.path.dirname(os.path.realpath(__file__))
# replace LIB_PATH definition
LIB_PATH = [libpath['find_lib_path']()[0].replace(CURRENT_ABSOLUTE + '/', '')]

I don't think I can locate setup.py anywhere in the system. Thanks much.

**Comment by andrewtcrooks** [comment]
I still have this exact problem despite following the instructions [here](https://github.com/dmlc/xgboost/blob/master/doc/build.md) exactly.

Happens to me on both Unbuntu 16.04 and OSX Yosemite both with anaconda python 3.6.

~/xgboost/python-package$ sudo /home/lokiz/anaconda/bin/python setup.py install
Install libxgboost from: ['../lib/libxgboost.so']
running install
running bdist_egg
running egg_info
writing xgboost.egg-info/PKG-INFO
writing dependency_links to xgboost.egg-info/dependency_links.txt
writing requirements to xgboost.egg-info/requires.txt
writing top-level names to xgboost.egg-info/top_level.txt
reading manifest file 'xgboost.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'xgboost/include'
warning: no files found matching '*' under directory 'xgboost/src'
warning: no files found matching '*' under directory 'xgboost/make'
warning: no files found matching '*' under directory 'xgboost/rabit'
warning: no files found matching '*' under directory 'xgboost/lib'
warning: no files found matching '*' under directory 'xgboost/dmlc-core'
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.a' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'xgboost.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/compat.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/sklearn.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/training.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/plotting.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/callback.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/libpath.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/VERSION -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/build-python.sh -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/__init__.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/core.py -> build/bdist.linux-x86_64/egg/xgboost
copying build/lib/xgboost/rabit.py -> build/bdist.linux-x86_64/egg/xgboost
byte-compiling build/bdist.linux-x86_64/egg/xgboost/compat.py to compat.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/sklearn.py to sklearn.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/training.py to training.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/plotting.py to plotting.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/callback.py to callback.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/libpath.py to libpath.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/core.py to core.cpython-36.pyc
byte-compiling build/bdist.linux-x86_64/egg/xgboost/rabit.py to rabit.cpython-36.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
copying ../lib/libxgboost.so -> build/bdist.linux-x86_64/egg/xgboost
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying xgboost.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/xgboost-0.6-py3.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing xgboost-0.6-py3.6.egg
removing '/home/lokiz/anaconda/lib/python3.6/site-packages/xgboost-0.6-py3.6.egg' (and everything under it)
creating /home/lokiz/anaconda/lib/python3.6/site-packages/xgboost-0.6-py3.6.egg
Extracting xgboost-0.6-py3.6.egg to /home/lokiz/anaconda/lib/python3.6/site-packages
xgboost 0.6 is already the active version in easy-install.pth

Installed /home/lokiz/anaconda/lib/python3.6/site-packages/xgboost-0.6-py3.6.egg
Processing dependencies for xgboost==0.6
Searching for scipy==0.19.1
Best match: scipy 0.19.1
Adding scipy 0.19.1 to easy-install.pth file

Using /home/lokiz/anaconda/lib/python3.6/site-packages
Searching for numpy==1.13.1
Best match: numpy 1.13.1
Adding numpy 1.13.1 to easy-install.pth file

Using /home/lokiz/anaconda/lib/python3.6/site-packages
Finished processing dependencies for xgboost==0.6





Is this supposed to be this way?

**Comment by Vanban-Wu** [comment]
We are running out of luck using MacBook for xgboost. I guess we either
have to use a PC to try out such feature or wait till the fix is available
for all MacBook users. Please let me know if you can find a better solution
to this problem. Thanks much.

Best regards,

Vanban

**Comment by andrewtcrooks** [comment]
I should have been a little clearer. 

The output above is on a "PC" with a quad core i7 processor with 6GB RAM and Ubuntu 16.04. 

I have also tried installation on my Macbook pro retina which has an i5 dual core and 8GB RAM using gcc-6 from brew with the --without-multilib option. I get that same "warning: no files found matching" in both cases.

**Comment by Vanban-Wu** [comment]
Andrew,

I have seen successful cases from other users, but they are using Python
3.5 instead of 3.6. So I guess xgboost only works with Python 3.5 so far
and not the newer version. I myself in interest to try out this new Machine
Learning mechanism. I guess we have to wait until a fix is available for
3.6. If you can find some new options, please do share. I will do the same.
Thanks and keep in touch.

By the way, I did try both Multi-Thread and single-thread, neither worked
on neither of my machines, MacBook Air and MacBook Pro (Siena version).

Best regards,

Vanban

**Comment by khotilov** [comment]
@andrewtcrooks I don't see any problem in your log (ignore the warnings). From there it looks like a happily installed package. Did you actually try using it?

**Comment by napsternxg** [comment]
A better fix is to to update the setup.py as follows:

```python
      data_files=[('xgboost', [os.path.relpath(p) for p in LIB_PATH])],
```

This is the final setup.py for the current stable release. 


```python
# pylint: disable=invalid-name, exec-used
"""Setup xgboost package."""
from __future__ import absolute_import
import sys
import os
from setuptools import setup, find_packages
# import subprocess
sys.path.insert(0, '.')

CURRENT_DIR = os.path.dirname(__file__)

# We can not import `xgboost.libpath` in setup.py directly since xgboost/__init__.py
# import `xgboost.core` and finally will import `numpy` and `scipy` which are setup
# `install_requires`. That's why we're using `exec` here.
libpath_py = os.path.join(CURRENT_DIR, 'xgboost/libpath.py')
libpath = {'__file__': libpath_py}
exec(compile(open(libpath_py, "rb").read(), libpath_py, 'exec'), libpath, libpath)

LIB_PATH = libpath['find_lib_path']()
print("Install libxgboost from: %s" % LIB_PATH)
# Please use setup_pip.py for generating and deploying pip installation
# detailed instruction in setup_pip.py
setup(name='xgboost',
      version=open(os.path.join(CURRENT_DIR, 'xgboost/VERSION')).read().strip(),
      # version='0.4a23',
      description="XGBoost Python Package",
      long_description=open(os.path.join(CURRENT_DIR, 'README.rst')).read(),
      install_requires=[
          'numpy',
          'scipy',
      ],
      maintainer='Hongliang Liu',
      maintainer_email='phunter.lau@gmail.com',
      zip_safe=False,
      packages=find_packages(),
      # this will use MANIFEST.in during install where we specify additional files,
      # this is the golden line
      include_package_data=True,
      data_files=[('xgboost', [os.path.relpath(p) for p in LIB_PATH])],
      url='https://github.com/dmlc/xgboost')

```
