### ISSUE TITLE
[jvm-packages] Memory leak

### ISSUE THREAD

**Issue by nikolay-karpow** [dmlc/xgboost#2178]
I run XGBoost model training on Spark standalone cluster. Cluster consists from two machines 16 cores and 256 Gb RAM each. For this particular round of experimenting I run 5 spark executors on each machine. Each executor has 6 gigs of memory (spark.executor.memory=6g) and a single core. So, executors should take 6*5 = 30 gb memory on each machine. Smth about 220 gb should be free. 

I have 28 datasets 3700 - 465000 elements each. Features count is 6000 - 20000. 
For each data set I run a training job, which consists from about 11-12 models training and bunch of predictions (both are with RDD). I've run all 28 datasets twice without application restart. I see, that memory consumption grows with each data set job completion. 

I looked at XGBoost.trainWithRDD method and specifically at DMatrix creation for each partition. DMatrix relies on finalize call in order to free the native memory. So, I've added `trainingDataSet.foreachPartition(it -> System.gc());` call after each train. I see FullGC in the executors logs, but memory consumption still grows. 

I look at the available memory (`free -g`, "available") on a single machine (the picture is quite similar for both of them). 
- The very first data set is completed: 216 gb is available
- First 15 data sets are completed: 196 gb is available
- All 28 data sets are completed for the first time: 168 gb is available.
- All 28 data sets are completed for the second time: 129 gb is available. 

After two runs for all 28 data sets each executor uses about 20-30 gb of memory instead of 6 specified by spark property. 

When I run 15 executors on each machine, the picture is similar, but there is not enough memory for the second run - OS starts to kill executors because of OutOfMemory. 

Is it a known issue? Is there a workaround for that?

## Environment info
Operating System:
CentOS 7.2

xgboost version used:
commit ef8d92fc52c674c44b824949388e72175f72e4d1 from Jan 9

Spark 2.0.2

**Comment by CodingCat** [comment]
There is a fishy cache() in the fucntion constructing boosters....I thought it had been removed...

**Comment by CodingCat** [comment]
when you file issues regarding xgboost4j, would you please add [jvm-pacakges] in the title so that I can quickly locate them?

**Comment by nikolay-karpow** [comment]
Sure, renamed

**Comment by CodingCat** [comment]
this should have been fixed by https://github.com/dmlc/xgboost/pull/2183

**Comment by nikolay-karpow** [comment]
I'm sorry, I haven't had a chance to check it earlier. I'm afraid, the issue is still there. This time I have 148 gigs available after the second run. It's a bit better, than before, but memory leak still exists...

**Comment by CodingCat** [comment]
Did you enforce full GC after the first run?

if you have done that, there might be some memory leak in native layer (assuming that you didn't cache anything )

**Comment by CodingCat** [comment]
see a similar report in: https://github.com/dmlc/xgboost/issues/2205

**Comment by nikolay-karpow** [comment]
I didn't force full GC, but it happened regularly, it's clear from executors logs. So, GC shouldn't be the reason for that.
`there might be some memory leak in native layer` - what can I do with that? Is there some known workaround? Are you working on fixing that?

**Comment by CodingCat** [comment]
If you didn't enforce Full GC, can you ensure that the boosters are collected before you measure the memory footprint? 

I am not looking at native layer stuffs

**Comment by nikolay-karpow** [comment]
I see in the executor logs, that Full GC happens every few hours. Given that the whole job takes about 2 days, I think, it's enough to be sure, that busters should be collected. What do you think?
