### ISSUE TITLE
model_.trees.size() < model_.trees_to_update.size()

### ISSUE THREAD

**Issue by Mary-Kul** [dmlc/xgboost#4700]
Hi, I have the following issue, training incremental XGBoost model, For some reason it works OK with with small amount of data, but when I make training set bigger it fails.

`xgboost.core.XGBoostError: [13:08:33] src/gbm/gbtree.cc:278: Check failed: model_.trees.size() < model_.trees_to_update.size() (159 vs. 159) : 
Stack trace:
  [bt] (0) 1   libxgboost.dylib                    0x0000000125d4f579 dmlc::LogMessageFatal::~LogMessageFatal() + 57
  [bt] (1) 2   libxgboost.dylib                    0x0000000125daf83c xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::__1::vector<std::__1::unique_ptr<xgboost::RegTree, std::__1::default_delete<xgboost::RegTree> >, std::__1::allocator<std::__1::unique_ptr<xgboost::RegTree, std::__1::default_delete<xgboost::RegTree> > > >*) + 620
  [bt] (2) 3   libxgboost.dylib                    0x0000000125dabfd0 xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*) + 320
  [bt] (3) 4   libxgboost.dylib                    0x0000000125d4b8be xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*) + 1518
  [bt] (4) 5   libxgboost.dylib                    0x0000000125d6a314 XGBoosterUpdateOneIter + 180
  [bt] (5) 6   _ctypes.cpython-37m-darwin.so       0x000000011237536f ffi_call_unix64 + 79
  [bt] (6) 7   ???                                 0x00007ffee6dd0b20 0x0 + 140732771666720`

the code for model
```python
params = { 'verbose': False,  'eval_metric': 'rmse', 'n_jobs':24, 'max_depth':params_xgb['all']['max_depth'],
                                 'min_child_weight':params_xgb['all']['min_child_weight'],
                  # 'learning_rate': 0.007,
                  'updater': 'refresh',
                  'process_type': 'update',
                  'refresh_leaf': True}
 model = xgb.train(params, dtrain=xgb.DMatrix(X_train, y_train), evals = watchlist,num_boost_round =300, early_stopping_rounds=20,
                          xgb_model=model,evals_result=progress, verbose_eval = 10)
```

xib model in the code is defined like this
```python
params = { 'verbose': False,  'eval_metric': 'rmse', 'n_jobs':24, 'max_depth':params_xgb['all']['max_depth'],
                                 'min_child_weight':params_xgb['all']['min_child_weight']}
model = xgb.train(params, dtrain=xgb.DMatrix(X_train,y_train), evals = watchlist, num_boost_round =300,early_stopping_rounds=20,
                          evals_result=progress,verbose_eval = 10)
```

I have Mac.os Mojave 10.14.3
python 3.7.4
xgboost 0.90

**Comment by trivialfis** [comment]
If you don't silent XGBoost it should give you a warning about using updater parameter.  The refresh updater is used to refresh built tree, not building new trees.  I suspect that's the problem.  :-)

**Comment by Mary-Kul** [comment]
@trivialfis it does warn but in incremental learning it is the point, isn't it? I want to update my trees not to increase amount of them according to the new data...

I do not understand why for some amount of data it works and for some - does not

Thanks in advance

**Comment by trivialfis** [comment]
I don't understand what you meant.  Model in boosting is fixed once learned.  You can't modified the built tree, only adding new ones is valid.

**Comment by Mary-Kul** [comment]
@trivialfis , here it is shown how incremental learning works https://gist.github.com/ylogx/53fef94cc61d6a3e9b3eb900482f41e0. Likewise my case here updater is "refresh"

**Comment by trivialfis** [comment]
@Mary-Kul Thanks.  Reopening so that we can take a closer look into it.

**Comment by trivialfis** [comment]
@Mary-Kul Could you provide a reproducible script?  I can't reproduce it on my end with 1M rows of data.

**Comment by trivialfis** [comment]
I ran the gist on master branch and it works fine. Should be fixed with new model IO routines.

**Comment by kevinkvothe** [comment]
> I ran the gist on master branch and it works fine. Should be fixed with new model IO routines.

It is not fixed for me, I keep having the same error even though the tree sizes are exactly the same (42), as you can see in the log:

```
/workspace/src/gbm/gbtree.cc:275: Check failed: model_.trees.size() < model_.trees_to_update.size() (42 vs. 42) : 
Stack trace:
  [bt] (0) /home/kubote/.local/lib/python3.8/site-packages/xgboost/./lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x54) [0x7fdef0686614]
  [bt] (1) /home/kubote/.local/lib/python3.8/site-packages/xgboost/./lib/libxgboost.so(xgboost::gbm::GBTree::BoostNewTrees(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, int, std::vector<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> >, std::allocator<std::unique_ptr<xgboost::RegTree, std::default_delete<xgboost::RegTree> > > >*)+0xe7f) [0x7fdef073592f]
  [bt] (2) /home/kubote/.local/lib/python3.8/site-packages/xgboost/./lib/libxgboost.so(xgboost::gbm::GBTree::DoBoost(xgboost::DMatrix*, xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::ObjFunction*)+0x121) [0x7fdef0737b91]
  [bt] (3) /home/kubote/.local/lib/python3.8/site-packages/xgboost/./lib/libxgboost.so(xgboost::LearnerImpl::UpdateOneIter(int, xgboost::DMatrix*)+0x3e1) [0x7fdef0772a11]
  [bt] (4) /home/kubote/.local/lib/python3.8/site-packages/xgboost/./lib/libxgboost.so(XGBoosterUpdateOneIter+0x29) [0x7fdef0675639]
  [bt] (5) /usr/lib/libffi.so.6(ffi_call_unix64+0x4c) [0x7fdf36a9b69a]
  [bt] (6) /usr/lib/libffi.so.6(ffi_call+0x196) [0x7fdf36a9afb6]
  [bt] (7) /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(+0xf11d) [0x7fdf36b0111d]
  [bt] (8) /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(+0x1383d) [0x7fdf36b0583d]
```

**Comment by trivialfis** [comment]
Let me take another look.

**Comment by trivialfis** [comment]
@kevinkvothe If you are running the latest XGBoost release without `silent`, there should be a warning saying parameter `update` is not used.  The correct parameter name should be `updater`.  To modify that notebook to run it correctly, first you need to train a model with `default` `process_type`, so that you can have some trees to update.  Then use `pruner` or `refresh` for updating existing trees.

**Comment by kevinkvothe** [comment]
> @kevinkvothe If you are running the latest XGBoost release without `silent`, there should be a warning saying parameter `update` is not used. The correct parameter name should be `updater`. To modify that notebook to run it correctly, first you need to train a model with `default` `process_type`, so that you can have some trees to update. Then use `pruner` or `refresh` for updating existing trees.

I'm going to share a notebook I made to test this error. It should be completely reproducible.

Btw, same error appears if I use `prune` as the `updater` parameter together with `update` as `process_type`.

[test.zip](https://github.com/dmlc/xgboost/files/4332594/test.zip)

**Comment by kevinkvothe** [comment]
So if I understand correctly, setting a fixed `num_boost_round` equal to the number of trees trained in the first model (the one we update over it) should solve the issue?

**Comment by trivialfis** [comment]
Yup.  The gist is don't update non-existing tree.

**Comment by luisvivasg** [comment]
I also get teh same error, but with 0.

heck failed: model_.trees.size() < model_.trees_to_update.size() (0 vs. 0)

I tried this after the first iteration but I get another error saying Get_booster is not a class of Boost.  

 dump_list = walmart_model.get_booster().get_dump()
    num_trees = len(dump_list)

**Comment by kings-shah** [comment]
model=None
params={'learning_rate': 0.007,
        'tree_method': 'exact',
           'refresh_leaf': True,
            #'reg_lambda': 3,  # L2
            'reg_alpha': 3,  # L1
            'silent': False}
for (i,j) in zip(X_train_list,y_train_list):
    dtrain=xgb.DMatrix(i,j)
    model=xgb.train(params, dtrain, num_boost_round=10, evals=(), obj=None, feval=None, maximize=False, early_stopping_rounds=None, evals_result=None, verbose_eval=True, xgb_model=model, callbacks=None)
    params={'learning_rate': 0.007,
        'tree_method': 'exact',
            'updater':'refresh',
            'process_type': 'update',
            'refresh_leaf': True,
            #'reg_lambda': 3,  # L2
            'reg_alpha': 3,  # L1
            'silent': False}


This worked for me. I hope its correct
