### ISSUE TITLE
Prebuilt R Package Binaries with GPU Support

### ISSUE THREAD

**Issue by jaredlander** [dmlc/xgboost#6654]
More attention is being paid to R on GPU so it would be great to have prebuilt binaries. I understand they cannot be hosted on CRAN, but many users are comfortable using `devtools::install_url()`. So if you could host it on the [releases](https://github.com/dmlc/xgboost/releases) page that would be a big help for two reasons: Many users are not comfortable using cmake. And, more importantly, more and more users use a library manager like `{renv}`, meaning that packages need to be rebuilt for each project. If a binary were available it could be reused for each.

`{catboost}` uses [this approach](https://catboost.ai/docs/installation/r-installation-binary-installation.html) for installing the R package from their [releases page](https://github.com/catboost/catboost/releases).

If I am reading the [installation file](https://github.com/dmlc/xgboost/blob/master/cmake/RPackageInstall.cmake.in#L34) properly, it looks like binary a file is built. Perhaps CI can build this and put the binary on the releases page?

Of course, finding a way to get the GPU version on CRAN is ideal, but I don't know how hard that is. Though there have been other packages on CRAN to make use of the GPU so I imagine it is possible.

Sorry if this has already been requested. I searched the issues but didn't quite see anything about this.

**Comment by hcho3** [comment]
Given the hard requirement of cross-platform support in CRAN, GPU support on CRAN is probably infeasible. On the other hand, it should be feasible to host an automated CI pipeline to generate a tarball with a pre-built binary. Thanks for your suggestion.

**Comment by jaredlander** [comment]
Oh yes, I saw the whole Solaris debacle. One of my packages, which "suggests" `{xgboost}`, almost got booted because of that. It is possible, if you ask the right maintainer nicely, to get the Solaris requirement waived. In fact, there is technically a rule that your package only has to pass checks on two OSes, but clearly that is unevenly applied.

The DESCRIPTION file has an optional field called `os_type`, which I thought would be helpful, but it only takes either unix or windows, and unfortunately Solaris is unix.

I wonder if there is a way to skip GPU checks on Solaris. I know that my packages now check the OS and run some examples and tests only for certain OSes.

Anyway, enough of my rambling, the pre-built binary via CI will be great! Thanks for taking that on!

**Comment by hcho3** [comment]
FYI I'm on vacation from Jan 29 to March 3, so during that time I won't be able to work on XGBoost.

**Comment by hcho3** [comment]
Another reason to keep the GPU code away from CRAN: we do not want to use `configure` to build the GPU code. The standard CRAN install still does not support the use of CMake and requires package maintainers to write a `configure` script instead. Getting CUDA build in a `configure` script is just too much of a hassle.

**Comment by jaredlander** [comment]
Figures there would be more hurdles for CRAN.

Enjoy the vacation! I look forward to checking out the CI build whenever it's done.

**Comment by hcho3** [comment]
@jaredlander 

> More attention is being paid to R on GPU

Can you point me to some use cases, tutorials, or talks in this space? Would love to know more, and find out how we can improve the user experience here.

**Comment by jaredlander** [comment]
So there's talks I've given https://jaredlander.com/content/2020/11/HoursToSeconds.html#1 and https://jaredlander.com/content/2018/03/AIDeepLearningR.html#1, then Neal Richardson mentioned it at [NYR](https://www.rstats.ai) https://youtu.be/p87NFQbTP-A, the new `{torch}` package uses the GPU (there was a talk at [nyhackr](https://www.meetup.com/nyhackr) last night), the `{keras}` package, both of which have GPU enabled on the CRAN package somehow, the `{gpuR}` package, has been around for a while but recently got pulled from CRAN, but that's been happening to a lot of packages as you know first hand. `{catboost}` has a binary with GPU ready to go and `{lightgbm}` is talking about doing that. There's RPUDPLUS, but that requires a license. Other packages include `{rgpu}` , `{MAGMA}`, `{OpenCL}`. There's a lot out there.

**Comment by hcho3** [comment]
Hello everyone, we invite you try out the pre-built R package binary with GPU support.

Prerequisite:
* CUDA Runtime 10.0 or later
* R 3.3.0 or later
* Linux 64-bit only, for now

1. Download the tarball from https://s3-us-west-2.amazonaws.com/xgboost-nightly-builds/PR-6827/xgboost_r_gpu_linux_8b120fc6ff8d5eae92a584b9f64ad04787de134c.tar.gz
2. If not installed already, install the dependencies for the R package:
```
R -q -e "install.packages(c('data.table', 'magrittr', 'jsonlite'))"
```
3. Install XGBoost:
```
R CMD INSTALL ./xgboost_r_gpu_linux_8b120fc6ff8d5eae92a584b9f64ad04787de134c.tar.gz
```

This should install XGBoost with full GPU support (`tree_method="gpu_hist"`).

Feel free to try it and let me know how it goes. Thanks!

cc @jaredlander

**Comment by jaredlander** [comment]
This is awesome! Can't wait to try this. Also going to build it into my training material.

**Comment by hcho3** [comment]
@jaredlander If nothing breaks in the next few days, I plan to release the pre-built binary in the upcoming 1.4.0 release.

**Comment by jaredlander** [comment]
Very excited for this.

**Comment by hcho3** [comment]
Hello everyone, we just release the 1.4.0 release. See the top of https://xgboost.readthedocs.io/en/latest/build.html for instructions to install XGBoost from the pre-built binary package. You can find the file `xgboost_r_gpu_linux_1.4.0.tar.gz` 
(74.3 MB) from the [Releases](https://github.com/dmlc/xgboost/releases/tag/v1.4.0) page.

**Comment by hcho3** [comment]
@jaredlander Did you have a chance to try it? How did it go? If you run into any issue, please let us know.

**Comment by jaredlander** [comment]
I've been so buried the past few weeks. I can give it a try Wednesday afternoon.

**Comment by hcho3** [comment]
Great! We've cleaned up the installation doc to display the binary package option more prominently: https://xgboost.readthedocs.io/en/latest/install.html#r

**Comment by adatum** [comment]
@hcho3 Thank you for this R GPU support! I checked it quickly and it seems to work fine. It is easier than the recursive cloning for the submodules and building from source.

**Comment by ssh352** [comment]
good news, waited too long!

**Comment by hcho3** [comment]
Hello everyone, we now offer a pre-built binary targeting the Windows platform as well. See the updated instrutions at https://xgboost.readthedocs.io/en/latest/install.html#id2.

**Comment by aegerton** [comment]
With apologies, I am just a hobbyist, but I am keen to try xgboost on Windows in R using my gpu.

When trying both the pre-built binary (as well as trying to build the package from source), I get the following error message;-

```
> install.packages("C:/Users/aeger/Downloads/xgboost_r_gpu_win64_4ddf8d001c5706c5f745aa9b5272278980ecefa9.tar.gz", repos = NULL, type = "source")
Installing package into ‘D:/OneDrive/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'xgboost' ...
** using staged installation
      0 [main] sh 960 C:\rtools40\usr\bin\sh.exe: *** fatal error - error while loading shared libraries: /usr/local/cuda/lib64/libnvblas.so: cannot open shared object file: No such file or directory
    467 [main] sh 960 cygwin_exception::open_stackdumpfile: Dumping stack trace to sh.exe.stackdump
ERROR: configuration failed for package 'xgboost'
* removing 'D:/OneDrive/Documents/R/win-library/4.1/xgboost'
Warning in install.packages :
  installation of package ‘C:/Users/aeger/Downloads/xgboost_r_gpu_win64_4ddf8d001c5706c5f745aa9b5272278980ecefa9.tar.gz’ had non-zero exit status
```
My CUDA toolkit is working fine, originally v11.4, but I have also installed v11.1 as well in case that is the problem.  I think that I have all the relevant entries on my PATH.

Any suggestions, please?

PS My curiosity was piqued by watching the recent excellent @jaredlander presentation on GPU Computing in R at the 2021 New York R Conference

**Comment by jaredlander** [comment]
Glad I got you motivated. For anyone who wants to see the install slide, it's at https://jaredlander.com/content/2021/09/GPUComputingWithR.html#62.

**Comment by aegerton** [comment]
Thanks very much @jaredlander for sharing the code.  It makes it much easier than retyping from the presentation!

Unfortunately, I'm still getting that same error message.  I am in Windows, not Linux, but I think that I have downloaded the right version of the batch file.

The error message keeps referring to this shared library libnvblas,so as being missing.

**Comment by vidarsumo** [comment]
I tried to use XGBoost for a regression problem (forecasting) in R using the tidymodels and modeltime package. The GPU version worked (the GPU load was 99%) but during tuning (using tune_race_anove) I got this error:
**Error in switch(object$params$objective, `binary:logitraw` = stats::binomial()$linkinv(res), : EXPR must be a length 1 vector**

Any idea what might be causing this without reprex?

**Comment by trivialfis** [comment]
It's a known issue in the released GPU binary, which has been fixed in latest and pending for complete tests on CRAN

**Comment by vidarsumo** [comment]
Hi @trivialfis, I installed the latest gpu version (xgboost_r_gpu_win64_afb9dfd4210e8b8db8fe03380f83b404b1721443.tar.gz)  but I'm still getting the same error, i.e.
**Error: Problem occurred during prediction. Error in switch(object$params$objective, `binary:logitraw` = stats::binomial()$linkinv(res), : EXPR must be a length 1 vector**

I saw it's build with cuda 11.0 but I have cuda 10.2. Does that matter here?

**Comment by trivialfis** [comment]
Sorry for the inconvenience.  I opened an issue https://github.com/dmlc/xgboost/issues/7489 , will get back to it.

**Comment by trivialfis** [comment]
@vidarsumo Could you please provide a reproducible example?  I'm trying to look into this.

**Comment by vidarsumo** [comment]
```
library(tidyverse)
library(tidymodels)
library(modeltime)
library(timetk)     # For the dataset

m750 <- m4_monthly %>% filter(id == "M750") %>% 
  tk_augment_lags(value, .lags = 1:12) %>% 
  drop_na() %>% 
  select(-id)

test_m750 <- m750 %>% tail(12)
train_m750 <- m750 %>% filter(!date %in% test_m750$date)

wflw_xgboost <- model_spec_xgboost_tune <- boost_tree(
  mode = "regression"
  ) %>%
  set_engine("xgboost", params=list(tree_method = 'gpu_hist')) %>% 
  fit(value ~ ., data = train_m750) %>% 
  modeltime_table()

wflw_xgboost %>% 
  modeltime_forecast(
    new_data = test_m750,
    actual_data = m750
  )

```
Results in this error:
**Error: Problem occurred during prediction. Error in switch(object$params$objective, `binary:logitraw` = stats::binomial()$linkinv(res), : EXPR must be a length 1 vector**


Session info

```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] xgboost_1.6.0.1    vctrs_0.3.8        rlang_0.4.12       finetune_0.1.0     yardstick_0.0.9    workflowsets_0.1.0 workflows_0.2.4    tune_0.1.6         rsample_0.1.1      recipes_0.1.17     modeldata_0.1.1   
[12] infer_1.0.0        dials_0.0.10       scales_1.1.1       broom_0.7.10       tidymodels_0.1.4   timetk_2.6.2       modeltime_1.1.0    parsnip_0.1.7      forcats_0.5.1      stringr_1.4.0      dplyr_1.0.7       
[23] purrr_0.3.4        readr_2.1.1        tidyr_1.1.4        tibble_3.1.6       ggplot2_3.3.5      tidyverse_1.3.1   

loaded via a namespace (and not attached):
 [1] minqa_1.2.4          colorspace_2.0-2     ellipsis_0.3.2       class_7.3-19         fs_1.5.1             rstudioapi_0.13      listenv_0.8.0        furrr_0.2.3          prodlim_2019.11.13   fansi_0.5.0         
[11] lubridate_1.8.0      xml2_1.3.2           codetools_0.2-18     splines_4.1.1        jsonlite_1.7.2       nloptr_1.2.2.3       pROC_1.18.0          dbplyr_2.1.1         compiler_4.1.1       httr_1.4.2          
[21] backports_1.4.0      assertthat_0.2.1     Matrix_1.3-4         cli_3.1.0            prettyunits_1.1.1    tools_4.1.1          gtable_0.3.0         glue_1.5.1           Rcpp_1.0.7           cellranger_1.1.0    
[31] DiceDesign_1.9       nlme_3.1-153         iterators_1.0.13     timeDate_3043.102    gower_0.2.2          globals_0.14.0       lme4_1.1-27.1        rvest_1.0.2          lifecycle_1.0.1      future_1.23.0       
[41] MASS_7.3-54          zoo_1.8-9            ipred_0.9-12         hms_1.1.1            parallel_4.1.1       StanHeaders_2.21.0-7 rpart_4.1-15         stringi_1.7.6        foreach_1.5.1        lhs_1.1.3           
[51] hardhat_0.1.6        boot_1.3-28          lava_1.6.10          pkgconfig_2.0.3      lattice_0.20-45      tidyselect_1.1.1     parallelly_1.29.0    plyr_1.8.6           magrittr_2.0.1       R6_2.5.1            
[61] generics_0.1.1       DBI_1.1.1            pillar_1.6.4         haven_2.4.3          withr_2.4.3          xts_0.12.1           survival_3.2-13      nnet_7.3-16          future.apply_1.8.1   modelr_0.1.8        
[71] crayon_1.4.2         utf8_1.2.2           tzdb_0.2.0           grid_4.1.1           readxl_1.3.1         data.table_1.14.2    reprex_2.0.1         digest_0.6.28        RcppParallel_5.1.4   GPfit_1.0-8         
[81] munsell_0.5.0 
```

**Comment by trivialfis** [comment]
@jaredlander I think it's in `parsnip`, it has this dispatching logic:

```
  x <- switch(
    object$params$objective,
    "binary:logitraw" = stats::binomial()$linkinv(res),
    "multi:softprob" = matrix(res, ncol = object$params$num_class, byrow = TRUE),
    res
  )
```

But the `object$params$objective` is `NULL` since you did not specify the objective function to use.  Quick workaround is to specify it (modified from your code):

``` R
wflw_xgboost <- model_spec_xgboost_tune <- boost_tree(
  mode = "regression"
) %>%
  set_engine("xgboost", params = list(tree_method = "gpu_hist", objective = "reg:squarederror")) %>%
  fit(value ~ ., data = train_m750) %>%
  modeltime_table()
```

A better solution would be modify the parsnip project (`modeltime` also uses a very similar function) to make a more robust dispatching like using `xgb.config` function to obtain the actual paramter.

**Comment by vidarsumo** [comment]
@trivialfis, this works perfectly :)
