### ISSUE TITLE
early.stop.round does not work properly

### ISSUE THREAD

**Issue by ganesh-krishnan** [dmlc/xgboost#726]
early.stop.round does not work if only one metric is provided. In fact, it seems like early.stop.round does not use the first metric for stopping when two metrics are provided. The source of both errors appears to be the same line of code.

```r
data(agaricus.train, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
history <- xgb.cv(data = dtrain, nround=3, nthread = 2, nfold = 5, metrics=list("rmse"),
                  max.depth =3, eta = 1, objective = "binary:logistic", early.stop.round=3)
```

This results in the following error:
> Error in strsplit(score, "\\+|:")[[1]][[2]] : subscript out of bounds

The issue seems to be the following line of code in xgb.cv:

```r
 score = strsplit(ret, "\\s+")[[1]][1 + length(metrics) + 2]
```

Changing that line to the following should fix it.

```r
score = strsplit(ret, "\\s+")[[1]][2 + length(metrics)]
```

**Comment by terrytangyuan** [comment]
Thanks for reporting. Which version of xgboost are you using? Do you want to submit a PR for this?

**Comment by ganesh-krishnan** [comment]
I'm using version 0.4.2. I just submitted the PR.

**Comment by terrytangyuan** [comment]
Fixed by #730

**Comment by ahmaurya** [comment]
Is this issue resolved in the current version of xgboost installed through CRAN? I got the same error on xgboost 0.4.3 recently installed from CRAN. The error goes away after removing early.stop.round argument.

> Error in strsplit(score, "\\+|:")[[1]][[2]] : subscript out of bounds

**Comment by semenoffalex** [comment]
Still have the same issue with version 0.4.4 installed from CRAN and github, both on Windows and Linux.

**Comment by zhugejun** [comment]
Have the same issue on Ubuntu 14.04.

**Comment by AbhishekSinghVerma** [comment]
I am getting this error while using 0.4.3 on x86_64-unknown-linux-gnu/64bit (64-bit) server. Please let us know if this error has been resolved. If so I need to ask server admin to update xgboost version.

**Comment by tomliptrot** [comment]
I am getting this error since updating to version  0.4-4 on Windows.
