### ISSUE TITLE
R xgboost wrapper doesn't pass maximize parameter to xgb.train

### ISSUE THREAD

**Issue by ielbert** [dmlc/xgboost#916]
R package xgboost version 0.4-3:

xgboost function takes maximize parameter but does not pass it to xgb.train:
Line from xgboost:
    bst <- xgb.train(params, dtrain, nrounds, watchlist, verbose = verbose, 
        print.every.n = print.every.n, early.stop.round = early.stop.round)

xgb.train then complains:
Error in xgb.train(params, dtrain, nrounds, watchlist, verbose = verbose,  : 
  Please set maximize to note whether the model is maximizing the evaluation or not.

**Comment by khotilov** [comment]
It was fixed in August https://github.com/dmlc/xgboost/commit/b0be833c7585177ee835ede70ae58b9c7e347282

**Comment by ielbert** [comment]
The [xgboost_0.4-3.tar.gz](https://cran.r-project.org/src/contrib/xgboost_0.4-3.tar.gz) at CRAN seems to still have this issue with maximize in xgboost.R

**Comment by thirdwing** [comment]
@ielbert Can you try the drat repo version?

```
install.packages("drat", repos="https://cran.rstudio.com")
drat:::addRepo("dmlc")
install.packages("xgboost", repos="http://dmlc.ml/drat/", type="source")
```

**Comment by rwarnung** [comment]
I see the same problem in the current version on CRAN, which I use via [mlr](http://stackoverflow.com/questions/39333609/setting-non-tunable-parameters-maximize-together-with-early-stop-round-in-mlr?noredirect=1#comment66006663_39333609).

**Comment by ielbert** [comment]
Yes, the problem is still there. I just hot-patch the function on the fly.
